### ISSUE TITLE
android端推送不成功

### ISSUE THREAD

**Issue by shs1989** [simple-rtmp-server/srs-sea#11]
我在服务端的配置文件如下 
```
# the streamer cast stream from other protocol to SRS over RTMP.
# @see https://github.com/simple-rtmp-server/srs/tree/develop#stream-architecture
stream_caster {
    enabled         on;
    caster          flv;
    output          rtmp://127.0.0.1/[app]/[stream];
    listen          8936;
}
```

![flv](https://cloud.githubusercontent.com/assets/3633714/9713487/393812b6-5584-11e5-83bc-e9ce7be08013.png)
启动后没有进程显示。
我换另外的config就可以 如图
![hls](https://cloud.githubusercontent.com/assets/3633714/9713495/50fc53e4-5584-11e5-8b42-1e099f3cf39c.png)

**Comment by winlinvip** [comment]
SRS说了，日志写到了 `./objs/srs.log`，把你的日志贴上来看看。

**Comment by shs1989** [comment]
![log](https://cloud.githubusercontent.com/assets/3633714/9724495/26afaed8-560b-11e5-8fc5-b7acaea01526.png)

unsupported directive stream_caster

**Comment by winlinvip** [comment]
请给出全部的日志。

**Comment by winlinvip** [comment]
你编译SRS时得用SRS2，并且打开配置，参考WIKI：https://github.com/simple-rtmp-server/srs/wiki/v2_CN_Streamer#build
