### ISSUE TITLE
华为honor6和mate7启动时崩溃

### ISSUE THREAD

**Issue by winlinvip** [simple-rtmp-server/srs-sea#5]
华为honor6和mate7启动时崩溃，无法启动编码器。

**Comment by winlinvip** [comment]
豹子哥在帮忙看。

**Comment by vmespace** [comment]
我大概知道原因在哪里。源码中在chooseVideoEncoder中对视频格式进行挑选，范围为if ((cf >= cc.COLOR_FormatYUV411Planar && cf <= cc.COLOR_FormatYUV422SemiPlanar))，但是在return new Camera.PreviewCallback()回调中只给出了3个格式的处理，其他的默认原样拷贝，这个时候会在onGetYuvFrame中执行bb.put(data, 0, data.length);时崩溃，系统显示Bufferoverflow。

我的修改是把选择范围缩小为下面有处理的三种格式就没问题了，至于为什么，我后面还要细看下，刚接触

**Comment by vmespace** [comment]
忘记说了，目前debug模式下视频挺卡的，release就流畅了

**Comment by winlinvip** [comment]
帮忙改好后，提交pull request呗。

**Comment by winlinvip** [comment]
我直接就合并到github了

**Comment by vmespace** [comment]
好的，我下午提一个

**Comment by winlinvip** [comment]
Great!

**Comment by winlinvip** [comment]
确认已经没有问题了。NB!

**Comment by zengxiangdong** [comment]
荣耀6plus的device在哪？谢谢各位大神

**Comment by winlinvip** [comment]
我用的我同事的手机测试的，没有问题了，我用的是华为G7.
